name: Native CI

on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches:
      - master
      - release/*

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - uses: Swatinem/rust-cache@v2
        with:
          key: "lint"

      - run: just fmt
      - run: just clippy

  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - uses: Swatinem/rust-cache@v2
        with:
          key: "test"

      - run: just test

  docs:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - uses: Swatinem/rust-cache@v2
        with:
          key: "docs"

      - run: just docs
