name: Native CI (buildjet)

on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches:
      - master
      - release/*

jobs:
  lint:
    runs-on: buildjet-64vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy


      - uses: taiki-e/install-action@v2
        with:
          tool: just

      - run: just fmt
      - run: just clippy

  test:
    runs-on: buildjet-64vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy


      - uses: taiki-e/install-action@v2
        with:
          tool: just

      - run: just test

  docs:
    runs-on: buildjet-64vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy


      - uses: taiki-e/install-action@v2
        with:
          tool: just

      - run: just docs
