name: Native CI (self-hosted)

on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches:
      - master
      - release/*

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3


      - run: just fmt
      - run: just clippy

  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3



      - run: just test

  docs:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3


      - run: just docs
